### PR TITLE
Fix build matrix

### PR DESCRIPTION
**Pull request by ocefpaf**
`conda-smithy` did not know how to handle the `skip` from this feedstock. I will investigate it later. This fixes it for now.

### CODE REVIEW

**Comment by Korijn** [comment]
Maybe it was the lowercase `true`?

**Comment by ocefpaf** [comment]
> Maybe it was the lowercase `true`?

Don't think so. I tried a few combinations here and could not get `conda-smithy` to work properly.

**Comment by jakirkham** [comment]
Are you referring to skipping Travis CI or the AppVeyor build matrix?

The former was only added in 1.0.0.

Not really sure what the issue was with the latter, but I don't see an issue when re-rendering using 1.0.1. Seems to keep only 64-bit builds as specified.

**Comment by Korijn** [comment]
The changes in this PR are not entirely correct, given the skip condition `osx or win32 or linux32`

* add 32-bit configurations to the build matrix on AppVeyor :no_entry_sign: 
* remove travis :white_check_mark: 

Given what @jakirkham said you might want to try again @ocefpaf?

**Comment by ocefpaf** [comment]
@Korijn I believe the bug in conda-smithy that created the issue was fixed. So let's close this and you can try the rerender.

**Comment by jakirkham** [comment]
Went ahead and added a re-rendering PR ( https://github.com/conda-forge/pyopcode-feedstock/pull/2 ) with `conda-smithy` version `1.0.0`.

**Pull request closed without merging**
